### ISSUE TITLE
Problems with model 1537px

### ISSUE THREAD

**Issue by exequiel222** [Gauravv97/CameraBlur#3]
Great job!!!

I have done all the steps mentioned but when I wanted to try the 1537px model in all my tests I get the following error:

```java 
2019-01-20 18:48:41.798 31057-31251/com.anondev.gaurav.camerablur E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[ImageTensor], outputs:[SemanticPredictions]
2019-01-20 18:48:41.801 31057-31251/com.anondev.gaurav.camerablur E/AndroidRuntime: FATAL EXCEPTION: IntentService[PortraitBlurService]
    Process: com.anondev.gaurav.camerablur, PID: 31057
    java.lang.IllegalArgumentException: ConcatOp : Dimensions of inputs should match: shape[0] = [1,129,129,256] vs. shape[1] = [1,193,145,256]
    	 [[{{node concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ResizeBilinear, aspp0/Relu, concat/axis)]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.runAndFetchMetadata(Session.java:276)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:220)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at com.anondev.gaurav.camerablur.DeeplabProcessor.GetBlurredImage(DeeplabProcessor.java:118)
        at com.anondev.gaurav.camerablur.PortraitBlurService.onHandleIntent(PortraitBlurService.java:73)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

* Has this happened to you?
* Is there any change to the code or some extra precondition for Tensor Flow?
* If you could give me a help I would be very grateful
* I'm missing something?

I'm looking to do something similar but without losing so much quality in the images.

Thank you!!!

**Comment by Gauravv97** [comment]
Hi @exequiel222 , I only tested the default model(1025 px) in the new app (DepthMultiplier .5) . In previous versions i did test all the models and found them to be working ,so I hoped that they will work this time too. Let me test them all and reach back to you(around this weekend).
If time is not an issue you can use older models which gives you better results albeit with longer time.
Else you can reduce the number of classes from the datasets and create your own model and do make sure you tweak the individual weights for each class else the results can be biased .

**Comment by exequiel222** [comment]
Hi @Gauravv97, thank you very much for the help and support.
I will try to do what you mention.
Anyway I will be attentive to your answer :)

**Comment by Gauravv97** [comment]
Hi @exequiel222 , still interested in making a better version.
I've searched around the net and found [this](http://hellodfan.com/2018/07/06/DeepLabv3-with-own-dataset/) article to be really helpful . You should look into it . You can modify the pascal dataset and reduce some classes by merging them to background and follow this links procedure ,you will be able to get some pretty good results with some finetuning..
